### ISSUE TITLE
discussion: rule - operation description triggers when operation has a summary instead of a description

### ISSUE THREAD

**Issue by TristanSpeakEasy** [daveshanley/vacuum#174]
Just interested to hear your thoughts on https://quobix.com/vacuum/rules/descriptions/operation-description/

This rule gets triggered if an operation doesn't have a description, regardless of it having a summary or not.

For our own API spec sometimes the APIs are really quite simple (a get that returns an object that is already well documented within its schema) and so we use a single line summary string only, without the need for a description that would end up just being a duplicate of the summary.

A lot of documentation tooling also treats the summary as you would expect if the description is absent

**Comment by daveshanley** [comment]
I am open to suggestions; I added this rule because there is a chronic lack of descriptions in most specs. I want to ensure there is a check for descriptions. However, it may not need to remain a warning, it could be downgraded to info.

What would you expect from this rule if you were to define its behavior?

**Comment by TristanSpeakEasy** [comment]
For me personally if both summary and description were missing then it would warn, but if summary is provided and description is missing its just an info level alert that providing a description would help even more with documentation.

**Comment by daveshanley** [comment]
After thinking about this a little more, I made the following change: The rule will fire if there is no description AND a summary
if there is no description, but a summary is supplied, then the rule won't fire.

This is because different people use description and summary differently; some lean on one, and others lean on the other. There is no way to force people to do one or the other, so now the rule is more flexible, only to get upset if both are left out. 

This update is available in v0.0.37
