### ISSUE TITLE
Vacuum doesn't catch missing references

### ISSUE THREAD

**Issue by TristanSpeakEasy** [daveshanley/vacuum#230]
Using the example below, no errors are returned when running `vacuum lint openapi.yaml -d`.

I would expect it to return an error mentioning that the component `Item` is not defined

```yaml
openapi: 3.0.3
info:
  title: Test
  version: 0.0.1
  description: test
servers:
  - url: https://httpbin.org
paths:
  /test:
    get:
      operationId: test
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Item'
```

**Comment by daveshanley** [comment]
Interesting! https://quobix.com/vacuum/rules/schemas/oas3-unused-component/ only checks for `component` schemas that have not been used. (bottom-up)

However, it does not check for the reverse (top-down). This is because vacuum does not  (currently) try to parse the spec into a model using `libopenapi`. If it did, it would discover the wrong references.

This would be an enhancement to the rule(s) that perform this check, so they would be bi-directional.

**Comment by daveshanley** [comment]
Please try `v0.1.0` and let me know how you get on.
