### ISSUE TITLE
Homebrew install failing?

### ISSUE THREAD

**Issue by designvoid** [daveshanley/vacuum#232]
Hi there - Homebrew seems to be unable to install Vacuum? Also, can't see it listed on their website?

**Comment by daveshanley** [comment]
Hi, 

To install `vacuum` via homebrew, they don't yet have us added on master list tools available, which is no problem - because we have our own cask that is set up and ready for you. 

`brew install daveshanley/vacuum/vacuum`

The `daveshanley/vacuum/vacuum` is the part you're looking for.

Should work just fine, and whenever you want the latest version of vacuum? Just type `brew upgrade vacuum`

https://quobix.com/vacuum/installing/

**Comment by designvoid** [comment]
Ahh weird - when I copy/pasted from the website I think it had some hidden rogue characters
 - thanks!!!

**Comment by daveshanley** [comment]
> Ahh weird - when I copy/pasted from the website I think it had some hidden rogue characters! Thanks!!
> 
> <img alt="image" width="517" src="https://user-images.githubusercontent.com/630948/212040484-6880a569-39f2-4f07-afe9-4d849e900a2f.png">


Interesting, this should be fixed on the website. Thanks for the heads up.
