### ISSUE TITLE
"cannot resolve reference" problem on nested openapi structure

### ISSUE THREAD

**Issue by shayan-eftekhari** [daveshanley/vacuum#251]
Hello,

I have the following folder structure:

.
├── my-api.yaml
├── schemas
    ├── object1.yaml
    └── object2.yaml

In my-api.yaml I reference object1 like this:
$ref: ./schemas/object1.yaml

In object1.yaml I reference object2 like this:
$ref: ./object2.yaml

vacuum can find object1.yaml but it cannot find object2.yaml and shows "cannot resolve reference" error.
I can imagine that vacuum tries to dereference object2.yaml based on its working directory which is the root of my project. However, it would be nice if it could open object2.yaml based on the directory in which it is referenced.
It may worth to mention that openapi-generator can easily follow my structure and generates the final code.

**Comment by daveshanley** [comment]
Hi, 

This is an issue that stems from https://github.com/pb33f/libopenapi (which is the library that powers vacuum under the covers).

Resolving remote and local references is now fully supported in the library (https://github.com/pb33f/libopenapi/issues/73), so what you're asking for is very much helped.

However, the new feature is not yet exposed in vacuum. The reason is that by default, resolving local or remote files that are referenced is turned off by default. It's a security risk try and automatically resolve them without explicit instruction to do so.

What is required is providing a flag to enable local/remote resolving, and if the references are remote, a Base URL needs to be provided so the resolver knows where to look for the remote files. A local working directory can also be supplied to allow the resolver to work outside the current working directory. 

I just have not had time to wire these things up yet. 

So I have tagged this as an enhancement because all that is required to make it work, is exposing base paths/urls as flags that can be passed into vacuum.

**Comment by daveshanley** [comment]
In `v0.0.54` this capability has been exposed via a new global flag `-p` or `--base`

This allows a base URL or a base path to a working directory. Full docs are here:
https://quobix.com/vacuum/commands/external-references/
