### ISSUE TITLE
Spectral-report path incorrect for OpenAPI paths containing periods

### ISSUE THREAD

**Issue by AdrianMachado** [daveshanley/vacuum#295]
## Problem
When running `vacuum spectral-report` on an OpenAPI file with paths that contain periods (ex. `/info/events.json`), any issues reported in the output will have an incorrect `paths` array (ex. `[ 'paths', '/info/events', 'json' ]`)

## Repro
Make an OpenAPI file with the path specified above

## Expected Result
The portion after the period should be part of the same path segment in the spectral report `['paths', 'info/events.json']`

## Additional Details
I believe the error stems from [here](https://github.com/daveshanley/vacuum/blob/main/model/results.go#L107). I believe that the Vacuum reports create a `path` by concatenating the JSON segments with periods - this doesn't seem safe since paths can end in file extensions, and OpenAPI doesn't specify that they can't. I suppose if you wanted to keep using `.` as a delimiter, you could replace the original `.` with  a special character - and invert this operation later, but this seems like layering on hacks. It might be better to use a two chat delim like `->` instead, which is far less likely to show up in a path or schema name

**Comment by daveshanley** [comment]
There isn't a way to cleanly 'unpick' this path because there is no way to know what is a file extension and what the separator is. This means going back to each function that performs checks on paths and then builds the path in a way that can be cleanly picked apart for spectral reports.

It means wrapping the path in a key so:

`$.paths./my/path.json.get`

becomes

`$.paths['/my/path.json'].get`

which can then cleanly be 'unpicked' and put into an array for spectral.

**Comment by daveshanley** [comment]
This should be mostly resolved in `v0.7.0`, Can you try again?

**Comment by AdrianMachado** [comment]
I'll give it a try next week when I free up! Thanks so much

**Comment by daveshanley** [comment]
Any luck with this?

**Comment by AdrianMachado** [comment]
Ill need a few more days to do this myself - but if you're in a rush, test with Twilio's APIs. They use periods a lot

**Comment by daveshanley** [comment]
I ran vacuum against multiple twilio API specs, all paths were correct and this can no-longer be replicated.
