### ISSUE TITLE
Add File Path output option 

### ISSUE THREAD

**Issue by ntotten** [daveshanley/vacuum#334]
Linting output includes the line numbers but not the file path. If the format of the Line/Column could be changed instead to include the file, the terminal output would be a deep link in VSCode to go right to the location of the lining error. 

For example, the below would be clickable in the terminal and open the file to the right location:

```
./my-oas.json:498:24
```

![CleanShot 2023-08-23 at 12 39 59@2x](https://github.com/daveshanley/vacuum/assets/282782/ccdca6de-5cf6-4c07-bd58-9717c4d69842)

More info here: https://code.visualstudio.com/docs/terminal/basics#_links

**Comment by daveshanley** [comment]
This is a great idea. Adding to the backlog.

**Comment by daveshanley** [comment]
in `v0.5.0` the `lint` command now __partially__ supports file paths. I say partially, because it only reports the correct file for **inline** specs only, as in single file specifications, not exploded ones. Exploded file location support is coming in a later release, so for now - this upgrade works perfectly for single file linting, but will not be accurate for an exploded spec that pulls in references from other files, vacuum still reports the 'root' file as the source (for now). 

This is what vacuum looks like inside an IDE now (I am using JetBrains here, but it should be the same for VSCode)

![Screenshot 2023-11-17 at 6 27 25 PM](https://github.com/daveshanley/vacuum/assets/187345/a5ee6a72-c267-47a2-a625-c19f7a547070)

**Comment by ntotten** [comment]
This is awesome. Super helpful change. Thanks!

**Comment by daveshanley** [comment]
This should now be accurate for all deeply nested files as well. vacuum knows how to look up nodes from external files and locate the origins of them.
