### ISSUE TITLE
Optional securitySchemes argument bearerFormat not supported

### ISSUE THREAD

**Issue by ndimares** [daveshanley/vacuum#352]
@daveshanley as per the title I noticed that bearerFormat is not supported by Vacuum. When bearerFormat is present, Vacuum complains:

`OpenAPI document invalid: additionalProperties 'scheme', 'bearerFormat' not allowed - `

**Comment by daveshanley** [comment]
I will investigate on the next bug run.

**Comment by daveshanley** [comment]
@ndimares would you be able to supply me with a small sample spec that I can use to re-create the issue so I can get this resolved for you?

**Comment by daveshanley** [comment]
I don't know how to re-create this issue, because I am unsure which rule is firing this, or where it is coming from, would you be able to share the spec with me?

Much thanks!

**Comment by ndimares** [comment]
@daveshanley sorry for the delay. Here's a spec: https://raw.githubusercontent.com/LogicGateTech/openapi/main/openapi.json

**Comment by daveshanley** [comment]
Thank you!

**Comment by daveshanley** [comment]
I loaded the spec in. I saw the violation. It's coming from the `oas3-schema` rule, which is a rule that checks the validity of the entire schema as is. The message being returned by vacuum is misleading and confusing, this is because this logic is provided by another library that validates JSON schemas., the results are raw and confusing - something I will work on for sure because this is not very helpful information. 


This is what is reported

```
# Schemas Issues

Line / Column | Severity | Message                                                           | Rule        | Path
(2693:16)     | error    | Schema: missing properties: '$ref'                                | oas3-schema | $.components.securitySchemes.basic
(2693:16)     | error    | Schema: missing properties: 'name', 'in'                          | oas3-schema | $.components.securitySchemes.basic
(2693:16)     | error    | Schema: additionalProperties 'scheme', 'bearerFormat' not allowed | oas3-schema | $.components.securitySchemes.basic
(2693:16)     | error    | Schema: not failed                                                | oas3-schema | $.components.securitySchemes.basic
(2693:16)     | error    | Schema: missing properties: 'flows'                               | oas3-schema | $.components.securitySchemes.basic
(2693:16)     | error    | Schema: additionalProperties 'bearerFormat', 'scheme' not allowed | oas3-schema | $.components.securitySchemes.basic
(2693:16)     | error    | Schema: missing properties: 'openIdConnectUrl'                    | oas3-schema | $.components.securitySchemes.basic
(2695:17)     | error    | Schema: value must be "openIdConnect"                             | oas3-schema | $.components.securitySchemes.basic.type
(2695:17)     | error    | Schema: value must be "oauth2"                                    | oas3-schema | $.components.securitySchemes.basic.type
(2695:17)     | error    | Schema: value must be "apiKey"                                    | oas3-schema | $.components.securitySchemes.basic.type
(2696:19)     | error    | Schema: does not match pattern '^[Bb][Ee][Aa][Rr][Ee][Rr]$'       | oas3-schema | $.components.securitySchemes.basic.scheme
```

This is all coming from the same few lines, which is here in the spec:

```
"securitySchemes": {
      "bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "API Token"
      },
      "basic": {
        "type": "http",
        "scheme": "basic",
        "bearerFormat": "Basic Token"
      }
    }
```

Here is the Schema for `HttpSecurityScheme` as defined by the OpenAPI 3.0.x schema (https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.0/schema.json#L1328)

```
 "HTTPSecurityScheme": {
      "type": "object",
      "required": [
        "scheme",
        "type"
      ],
      "properties": {
        "scheme": {
          "type": "string"
        },
        "bearerFormat": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": [
            "http"
          ]
        }
      },
      "patternProperties": {
        "^x-": {
        }
      },
      "additionalProperties": false,
      "oneOf": [
        {
          "description": "Bearer",
          "properties": {
            "scheme": {
              "type": "string",
              "pattern": "^[Bb][Ee][Aa][Rr][Ee][Rr]$"
            }
          }
        },
        {
          "description": "Non Bearer",
          "not": {
            "required": [
              "bearerFormat"
            ]
          },
          "properties": {
            "scheme": {
              "not": {
                "type": "string",
                "pattern": "^[Bb][Ee][Aa][Rr][Ee][Rr]$"
              }
            }
          }
        }
      ]
    },
```

The problem isn't actually a problem, it's a valid failure of the schema., it's just that vacuum is reporting it from the bubble of a mess that's extracted from the underlying schema violation. 

To your key issue: `OpenAPI document invalid: additionalProperties 'scheme', 'bearerFormat' not allowed`

As you can see from the schema, it's NOT allowed when the type is not `bearer`. On line 2697 of the spec, the `basic` scheme has 'bearerFormat' defined, and the JSON schema declares that unless the `scheme` of the `securityScheme` is `bearer` then do not allow the inclusion of `bearerFormat`

If line 2697 is removed, there are no more violations of the schema. 

So the problem is really that vacuum is spitting out a ton of noise, for a single violation. But the violation is real and accurate according to the specification.

**Comment by ndimares** [comment]
Thanks for the thorough analysis @daveshanley !
