### ISSUE TITLE
memory usage

### ISSUE THREAD

**Issue by ramarro123** [daveshanley/vacuum#572]
Hi,

there is an "idea" on how much memory vacuum use to parse let's say a 1MB openapi specs? i know it's a "rough" extimation but i did try it and it eat 3gb, i am wondering if it's the real things or if there are something weird on my side

**Comment by daveshanley** [comment]
This is a very timely issue. Literally about to merge this. 

https://github.com/pb33f/libopenapi/pull/342

The reason why it's chewing up so much memory, is because of the model graph, references are (currently) being re-created over and over and over, which allocates an identical chunk of memory over and over. 

This is wrong because the ref doesn't change after it's built once, so now we have a cache in place to prevent this from happening. For example the docusign API chewed up 7GB. insane! mainly because the graph has millions and millions of reference cycles. 

This update should reduce memory use dramatically, but it doesn't solve the problem completely. vacuum chews up a bunch of memory because it walks the model under the hood, which creates the over production of schemas. 

Should be updated today, let me know how it helps once it's pushed.

**Comment by daveshanley** [comment]
v0.14.2

**Comment by ramarro123** [comment]
very late feedback, sorry

with 0.14.2 the memory usage of runner went down thanks!
