### ISSUE TITLE
regex escaping discrepancies

### ISSUE THREAD

**Issue by geemus** [daveshanley/vacuum#574]
I ran into some discrepancies between spectral and vacuum when it comes to regex from yaml, particularly around escaping.

First the details:

I think the repro case would be a pattern like: `'[@/-/.]'`.

- Spectral sees this as valid and matches/validates examples as I would expect.
- Vacuum says this isn't ECMA compliant. If I dig into the code and duplicate the error, it appears to be treating this as though it were `"[@/-/.]"`. ie that it is something that needs escaping and isn't escaped. As such it fails because it thinks that the hyphen is a broken character class instead of a literal hyphen.

I first tried changing it to: `'[@//-//.]'`

- Spectral sees that as a valid regex, but then doesn't match against what I would expect.
- Vacuum both sees it as valid and matches what I expect.

I was able to workaround this by changing the patterns to: `"[@//-//.]"`.

- Spectral both sees it as valid and matches what I expect.
- Vacuum both sees it as valid and matches what I expect.

From looking around at various docs, I think the Spectral behavior is technically more correct. ie a single quoted regex body here probably should be interpreted as not needing to be escaped and single vs double quoted probably do deserve different treatment.

I tried to figure out a fix, but didn't have much luck. I'd be happy to try again if you want to proceed in that direction, but I might need some help (or feel free to do it yourself). Conversely if it's not something you plan to fix, I thought documenting it might help others in the future.

**Comment by daveshanley** [comment]
Thanks for this. I won't be able to fix this myself, not at first glance.

I don't actually control any of the code that executes this. What happens under the covers is that vacuum actually tries to compile a regular expression in javascript in the same VM that powers vacuum JS functions (https://quobix.com/vacuum/api/custom-javascript-functions/)

If the regular expression compiles, it's marked as ECMA compliant, otherwise - well you get the drift. 

The actual regular expression execution (from the rule and the location etc) is performed by go, which is a straight passthrough, if it compiles and runs, it's all good etc. 

I'm just asking the computer "is this good in both JS and go and does this find anything?"

vacuum is not actually a clone or a replacement for spectral, it's very similar and does match most of it's core functionality, but vacuum is a different tool with a different design.

I will tag this as documentation and close it.

**Comment by geemus** [comment]
Hey, I was still running into this, so I wanted to circle back.

I totally understand that you are just handing this off to JS. I think the issue I was running into is that you are doing that handoff in a way that always treats it as a double quoted (and thus escaped) regex. I think it's also valid from the spec/etc to use a single quoted (and non-escaped) regex. In many cases it can be a bit easier to do this if you can, since escaping can get pretty unwieldy.

So I think the behavior I want is basically, pass it to JS with the same quoting it started with (rather than interpolating it into double quotes). It's not really about compatibility with the other tools, so much as I think it might be a bug in how it treats regex in general (that I happen to be running into because of other tools in this case).

Does that make any more sense/help?
