### ISSUE TITLE
Property pattern regex getting validation failed.

### ISSUE THREAD

**Issue by fud** [daveshanley/vacuum#585]
I'm getting a validation error for a properties regex pattern, `^(?=.{1,19}$)[0-9]{0,19}(?:\.[0-9]{0,18})?$`. 

`go/domains/external/v2/xxxx/xxx.yaml:861:11  | error    | schema invalid: validation failed | oas3-schema | Schemas  | $.components.schemas['activeCurrencyAndAmount'].properties['amount']`. It doesn't really give me the actual error sadly, but when I comment out this field in my schema it's the `pattern:` field that was causing the issue.

I'm a little confused why it's failing as I produced a standalone test with this code that is roughly the same as what I believe is happening in the code `functions/openapi/schema_type.go`

```
package main

import (
	"fmt"
	"strings"

	"github.com/dop251/goja"
)

func main() {

	r := `^(?=.{1,19}$)[0-9]{0,18}(?:\\.[0-9]{0,2})?$`

	vm := goja.New()
	script := strings.Replace("const regex = new RegExp('{pattern}');", "{pattern}", r, 1)
	_, err := vm.RunString(script)
	if err != nil {
		fmt.Println(err) 
	} else {
    fmt.Println("VALID")
  }
}

```

It prints `VALID`

**Comment by daveshanley** [comment]
I am having trouble re-creating this. I can't trigger it. Can you give me an example snippet of your spec that works as a recreation.

**Comment by daveshanley** [comment]
Well, using the [OpenAPI Doctor ](https://pb33f.io/doctor/)(which uses vacuum underneath) I was able to trigger it. 

![Screenshot 2024-11-21 at 11 54 20 AM](https://github.com/user-attachments/assets/baab98c3-0606-4c16-bf9a-3c62493d8994)

```
"file:///schema.json#" is not valid against metaschema: jsonschema validation failed with 'https://json-schema.org/draft/2020-12/schema#'

at '': allOf failed
at '/pattern': '^(?=.{1,19}$)[0-9]{0,18}(?:\\.[0-9]{0,2})?$' is not valid regex: error parsing regexp: invalid or unsupported Perl syntax: (?=
```

This validation is coming from https://github.com/santhosh-tekuri/jsonschema and it's getting upset because the format is not perl compatible, according to: https://json-schema.org/draft/2020-12/schema

The reason why your code works, is because you're using a JS engine (which we use in vacuum) to compile the regular expression (which works), however when we try and compile that same regex into go (which is how the schema validator is compiling the regex) it fails. 

I created a test that show this. 

```go
func TestPattern_RunRule_Issue585(t *testing.T) {

	sampleYaml := `no: 
  sleep: 123.45`
	path := "$.no"
	nodes, _ := utils.FindNodes([]byte(sampleYaml), path)
	assert.Len(t, nodes, 1)

	opts := make(map[string]string)
	opts["match"] = `^(?=.{1,19}$)[0-9]{0,18}(?:\\.[0-9]{0,2})?$`

	rule := buildCoreTestRule(path, model.SeverityError, "pattern", "sleep", opts)
	ctx := buildCoreTestContextFromRule(model.CastToRuleAction(rule.Then), rule)
	ctx.Given = path
	ctx.Rule = &rule

	def := &Pattern{}
	res := def.RunRule(nodes, ctx)

	assert.Len(t, res, 1)
	assert.Equal(t, "test rule: `^(?=.{1,19}$)[0-9]{0,18}(?:\\\\.[0-9]{0,2})?$` cannot be compiled into a "+
		"regular expression [`error parsing regexp: invalid or unsupported Perl syntax: `(?=``]", res[0].Message)
}
```
So the issue is that the regex is JS friendly, but not compatible with go. 

Here is a verification on regex101

![Screenshot 2024-11-21 at 12 01 28 PM](https://github.com/user-attachments/assets/760a642e-459d-47a8-a1d2-4052653df4da)

**Comment by daveshanley** [comment]
https://github.com/google/re2/wiki/Syntax

**Comment by fud** [comment]
Thanks @daveshanley that makes sense.
